name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8
  RUBY_VERSION: 2.6.x

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: macOS-latest
    env:
      XCODE_PROJECT: DictionaryCoder.xcodeproj
      IOS_SCHEME: DictionaryCoder iOS
      IOS_DESTINATION: OS=13.3,name=iPhone 11 Pro
      IOS_BUILD_LOG_PATH: xcodebuild-ios.json
      MACOS_SCHEME: DictionaryCoder macOS
      MACOS_DESTINATION: platform=macOS
      MACOS_BUILD_LOG_PATH: xcodebuild-macos.json
      TVOS_SCHEME: DictionaryCoder tvOS
      TVOS_DESTINATION: OS=13.3,name=Apple TV 4K
      TVOS_BUILD_LOG_PATH: xcodebuild-tvos.json
      SKIP_SWIFTLINT: TRUE
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          gem install bundler
          bundle install --without=documentation
      - name: Swift version
        run: |
          set -o pipefail
          swift --version
      - name: Tests - iOS
        run: |
          xcodebuild clean build test -project "$PROJECT" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="$IOS_BUILD_LOG_PATH" xcpretty -f `xcpretty-json-formatter`
          bash <(curl -s https://codecov.io/bash) -cF ios -J 'DictionaryCoder'
      - name: Tests - macOS
        run: |
          xcodebuild clean build test -project "$PROJECT" -scheme "$MACOS_SCHEME" -destination "$MACOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="$MACOS_BUILD_LOG_PATH" xcpretty -f `xcpretty-json-formatter`
          bash <(curl -s https://codecov.io/bash) -cF osx -J 'DictionaryCoder'
      - name: Tests - tvOS
        run: |
          xcodebuild clean build test -project "$PROJECT" -scheme "$TVOS_SCHEME" -destination "$TVOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="$TVOS_BUILD_LOG_PATH" xcpretty -f `xcpretty-json-formatter`
          bash <(curl -s https://codecov.io/bash) -cF tvos -J 'DictionaryCoder'
      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger --remove-previous-comments

  Cocoapods:
    name: Cocoapods
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          gem install bundler
          bundle install --without=documentation
      - name: Linter
        run: bundle exec pod lib lint --skip-tests --allow-warnings

  SPM:
    name: Swift Package Manager
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Test
        run: swift test
